### ISSUE TITLE
The graph ids in which sub-graphs are present is not listed in the final output with each subgraph

### ISSUE THREAD

**Issue by parnikadamle** [Jokeren/DataMining-gSpan#11]
Hi Jokeren,

I am a research scholar at V.N.I.T, Nagpur, India and I am using your gspan code in my work.
Currently in the final output, the ids of the graphs in which sub-graphs are present are not listed with each sub-graph. 
Also, both the output as well as logs are written to the same file.

Could you please make a provision in the code to include the graph ids along with each sub-graph in the output and write the output to a separate file?

It will be really helpful if you can provide these changes at the earliest.
Appreciate your help in advance.

**Comment by Jokeren** [comment]
Well, thank you for your attention, I will add these features. 

But currently I am busy finishing my paper work, as the deadline is coming soon. Thus I plan to handle your issue soon in early February. I promise that I will consider all the features you submitted.

**Comment by parnikadamle** [comment]
Hi Jokeren,

Sure no problem. I will wait for the modified code.
Thanks a lot for your quick response and help :)

**Comment by parnikadamle** [comment]
Hi Jokeren,

In my earlier post I requested two changes:-

1) include the graph ids along with each sub-graph in the final output
2) write the output to a separate file.

Every sub-graph present in the final output will always have exactly one
lexicographic parent sub-graph from which the current sub-graph is obtained.

For example, current output has below details:-

t # 3 \* 75
v 0 9
v 1 9
v 2 9
e 0 1 0
e 1 2 0

The lexicographic parent sub-graph from which above sub-graph is derived
will be

t # 1 \* 80
v 0 9
v 1 9
e 0 1 0

So, if feasible for you, could you please also include the Id of the parent
sub-graph along with the other details for each sub-graph in final output?

Also, can you please give this third change along with previous two changes
?

Appreciate your help in advance.

On Thu, Jan 21, 2016 at 9:57 PM, parnika paranjape <
parnikaparanjape@gmail.com> wrote:

> Hi Jokeren,
> 
> Sure no problem. I will wait for the modified code.
> Thanks a lot for your quick response and help :)
> On Jan 21, 2016 21:13, "Keren Zhou" notifications@github.com wrote:
> 
> > Well, thank you for your attention, I will add these features.
> > 
> > But currently I am busy finishing my paper work, and the deadline is
> > coming soon. Thus I plan to handle your issue soon in early February. I
> > promise that I will consider all the features you submitted.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/Jokeren/DataMining-gSpan/issues/11#issuecomment-173611012
> > .

## 

Regards
Parnika Paranjape

**Comment by parnikadamle** [comment]
Hi Jokeren,

Just a gentle reminder.

Can you please take a look at my previous post and help me with the listed issues at the earliest?

Appreciate your help in advance.

**Comment by Jokeren** [comment]
@parnika26 Hi, I have just finished my paper. Thank you for reminding. Tomorrow is Chinese New Year Festival, and I also wish you good luck!

**Comment by parnikadamle** [comment]
Hi Keren,

Thanks a lot for your quick response.
Wish you a Happy New and prosperous year.
Please let me know when you are done with the changes.
Sorry for the trouble but I need to use those changes in my research work.
Hence, waiting on you :)

Good luck for your paper :)

Appreciate your help in advance.

**Comment by Jokeren** [comment]
I plan to deal with them from tomorrow on, don't worry. :)

**Comment by parnikadamle** [comment]
Hi Keren,

Thank you so much :)

**Comment by Jokeren** [comment]
Please checkout the refine branch, including first two features.
https://github.com/Jokeren/DataMining-gSpan/tree/refine

**Comment by parnikadamle** [comment]
Hi Keren,

Thanks a lot for the help so far.
I have downloaded the modified code and tried running it. It runs fine.

But I see that the output is written to multiples files [For
ex,Chemical_3400, Chemical_3401, Chemical_3402, Chemical_3403] . Also, the
sub-graphs in these output files are currently written as follows:-

```
t # 3 * 75
parent graphs:
40 42 46 47 50 51 53 57 58 68 96 102 103 120 141 147 149 150 151 153
```

163 165 166 171 173 176 177 178       185 186 187 190 192 193 206 208 210
215 221 226 238 297 302 308 337
    v 0 9
    v 1 9
    v 2 9
    e 0 1 0
    e 1 2 0

_Could you please make below changes in the code?_

1) Write output to a single file instead of multiple files.

2) Write each sub-graph in below format [Old label 'parent graphs' , new
label 'x'. List of graph Ids at the end after writing edges]

```
t # 3 * 75
v 0 9
v 1 9
v 2 9
e 0 1 0
e 1 2 0
x: 40 42 46 47 50 51 53 57 58 68 96 102 103 120 141 147 149 150 151 153
```

163 165 166 171 173 176 177      178 185 186 187 190 192 193 206 208 210
215 221 226 238 297 302 308 337

3) As mentioned in earlier post, include the Id of the lexicographic parent
sub-graph along with the other details for each sub-graph in final output.

The lexicographic parent sub-graph from which above sub-graph is generated
will be,
     t # 1 \* 80
     v 0 9
     v 1 9
     e 0 1 0
     x: <some list of graph ids>

 After including parent id, each sub-graph written to output will then
appear in below format,
     t # 3 \* 75
     parent id: 1
     v 0 9
     v 1 9
     v 2 9
     e 0 1 0
     e 1 2 0
     x: 40 42 46 47 50 51 53 57 58 68 96 102 103 120 141 147 149 150 151
153 163 165 166 171 173 176 177      178 185 186 187 190 192 193 206 208
210 215 221 226 238 297 302 308 337

Appreciate your help in advance.

On Sun, Feb 7, 2016 at 12:40 PM, Keren Zhou notifications@github.com
wrote:

> Please checkout the refine branch, including first two features.
> https://github.com/Jokeren/DataMining-gSpan/tree/refine
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Jokeren/DataMining-gSpan/issues/11#issuecomment-180965654
> .

## 

Regards
Parnika Paranjape

**Comment by Jokeren** [comment]
Check out first two features.

I have to modify plenty of codes for the third feature, so it is currently in progress.

**Comment by parnikadamle** [comment]
Hi Keren,

Thanks a lot for the changes.
I have checked first two features and they are fine.

Just a small change.
Instead of writing graph ids on the new line after label 'x:' , can you
please write them on the same line as shown below ?

x 12 26 36 42 52 62 63 64 72 86 92 96 104 112 123 154 162 166 174 181 192
210 221 236 243 252 259 265 270 273 278 282 289 294 307 329

But I am in no hurry for this change. So, even if you give this change
along with the changes for third feature I am okay with it.

Thank you so much Keren :)

On Tue, Feb 9, 2016 at 8:37 AM, Keren Zhou notifications@github.com wrote:

> Check out first two features.
> 
> I have to modify plenty of codes for the third feature, so it is currently
> in progress.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Jokeren/DataMining-gSpan/issues/11#issuecomment-181685575
> .

## 

Regards
Parnika Paranjape

**Comment by Jokeren** [comment]
parent graph id updated @parnika26

**Comment by parnikadamle** [comment]
Hi Keren,

I have downloaded the modified code and tried running it.
It runs fine and gives desired output.

Thank you so much for the help so far :)
It was nice working with you.

In future, if I need some help I will get back to you :)

Once again thanks a lot.

On Wed, Feb 10, 2016 at 9:01 AM, Keren Zhou notifications@github.com
wrote:

> parent graph id updated @parnika26 https://github.com/parnika26
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Jokeren/DataMining-gSpan/issues/11#issuecomment-182182389
> .

## 

Regards
Parnika Paranjape
