### ISSUE TITLE
Split thread error

### ISSUE THREAD

**Issue by dionman** [Jokeren/DataMining-gSpan#15]
Running the code on 
[gspan.txt](https://github.com/Jokeren/DataMining-gSpan/files/964668/gspan.txt)
I am receiving split thread error! size 1, thread_size 4

What is the problem in this?

Kind regards,
Dionysis

**Comment by Jokeren** [comment]
I have not updated this repository for long time. Let me have a look.

**Comment by Jokeren** [comment]
Hi, @dionman , after examining my codes, I notice this error happens because of the `ProjectionMap` size. That is, the original projection map only contains one start point greater than the support value, so it cannot be split by four threads. I think it will be fine after adjusting the thread number (`THREAD_NUM`) to 1.

**Comment by Jokeren** [comment]
@dionman you can try our new version--gBolt now, I believe it could satisfy your requirements now, by setting any number of thread as you need.

**Comment by Jokeren** [comment]
@dionman , Hi, have you solved your data?

I have tried it, but it appears that as your edge labels and vertex labels are all 1, gspan cannot efficiently solve the problem.

**Comment by dionman** [comment]
Hi Keren,

Thanks for your interest. Can I use the node degree as the node label?
Moreover, can I apply the algorithm on directed networks?

**Comment by Jokeren** [comment]
1. Yes, you can. Whereas, you have to know that if all labels are the same, gspan may not have the capability to find FSMs. Indeed, as FSM is an NP problem, I think only approximate algorithms could solve it in that case.

2. Yes, the algorithm could be applied to directed networks. However, I have not implemented the feature yet. If you need it soon, you could use other repositories, which are not so fast. I will put this issue on my schedule, but sorry that I should concentrate on other projects this month.
