### ISSUE TITLE
Error while trying to run gbolt

### ISSUE THREAD

**Issue by yz555** [Jokeren/DataMining-gSpan#25]
Hello Keren, I met the problem that Segmentation fault (core dumped) occurred when I used my data which followed the format you asked, and I have no idea why this error occurred. I also tried different set OMP_NUM_THREADS=4, or 1 or 8, but all gave me the same error. I attached my data file here, would you please let me know if I am doing anything wrong? 
The command I used:
yzhang@codec:~/gBolt$ ./build/gbolt -i extern/data/combined10-3month.txt -s 0.2 -d -n -o extern/results/test10

Regards,
Yueqing
[combined10-3month.txt](https://github.com/Jokeren/gBolt/files/3794501/combined10-3month.txt)

**Comment by Jokeren** [comment]
@yz555, The graph ids you provided are not in sequence.

You have t # 0, t # 1, the following graph is t # 10 while the correct graph should be t # 2.

However, I am not sure if gBolt could handle your case. It ran forever on my machine.

Try gaston and please let me know what you find.

http://liacs.leidenuniv.nl/~nijssensgr/gaston/download.html

**Comment by yz555** [comment]
@Jokeren Thank you Keren, I will try gaston and will let u know if I find it works.

**Comment by yz555** [comment]
@Jokeren I found the Known Issue of Gaston on its Readme.file. It is infeasible to handle more than 64 edges, while in my file, almost every graph has more than 64 edges since each graph contains more than 100 nodes on average. Besides your C++ efficient implementation of gSpan alogorithm, I also tried python implementation of gSpan (https://github.com/betterenvi/gSpan), it was stuck when I set minimum support to 30% using 2850 large graphs. Do you know what else can I do to solve this large and sparse graph mining issue? 
![gatson-issue](https://user-images.githubusercontent.com/26554051/67978693-1173c280-fbf1-11e9-9d23-1c9c8ce51be8.PNG)

**Comment by Jokeren** [comment]
Try to invent a new algorithm and publish a paper by yourself?

There are several optimizations we could do for gBolt:

1. Use iterative patterns instead of recursive calls.
2. Implement some ideas from Gaston.
3. Write files during execution. 

However, if the number of frequent graphs is expected to be large, then probably there's no way to optimize. Maybe you can selectively output only a portion of the result.

**Comment by yz555** [comment]
@Jokeren Keren, thank you very much for your explanation and suggestion. If have difficulties to optimize it, would you please help me later LOL.

**Comment by Jokeren** [comment]
Unfortunately, I may not have free time slots to optimize gBolt at this moment. I can provide advice if you would like to do some work.

**Comment by thinhtpq** [comment]
Hello Keren, 
I met problem Segmentation fault (core dumped) when I ran gBolt with my dataset. It includes two graphs and their ID is sequence. I attached file below. Would you please let me know what it wrong?
[gSpan_Thinh.txt](https://github.com/Jokeren/gBolt/files/4239553/gSpan_Thinh.txt)

Best regards.
Thinh

**Comment by Jokeren** [comment]
@thinhtpq , there is an empty line between two graphs `t # 0` and `t # 1`.

**Comment by thinhtpq** [comment]
@Jokeren: It works! Thank you very much.
