### ISSUE TITLE
data properties

### ISSUE THREAD

**Issue by mohsenuss91** [Jokeren/DataMining-gSpan#3]
@Jokeren can you give more details about the properties of each used data  (The number of unique labels graphs in the dataset, The averaged size (the number of edges) of each graph. The density of each graph ...and more if possible) please ?

**Comment by Jokeren** [comment]
Sorry, currently I could just say I cannot. This is because the dataset is provided by my instructor, who hasn't told me the properties of the graph. 

But I think the properties you mentioned could be calculated by extended modules. So If you need those properties, please list them out. I will update them in the next version.

**Comment by mohsenuss91** [comment]
@Jokeren  OK, as a mentionned the most important properties are: The number of unique labels graphs , the averaged size (the number of edges) and the density of each graph.

**Comment by Jokeren** [comment]
This first property--"unique labels graphs", could you explain it specifically? Or present an example?

If you mean the graphs inside the original data, I think they are all different from each other.

**Comment by mohsenuss91** [comment]
@Jokeren  I mean edge's labels. for example if a graph has an edge with "A" as a label, "A"  cannot be fount in another graph so its a unique label dataset.

**Comment by Jokeren** [comment]
let us take the following two graphs as example:

t # 0
v 0 0
v 1 0
e 0 1 1
t # 1
v 0 0
v 1 0
e 0 1 0

As you mentioned above, '0' is a unique label dataset in t2, right? If so, we have to compare a graph with the rest of graphs in a file to generate the unique label dataset? So the final result would be a number of comparisons between graph $$t_{0}-t_{1}$$, $$t_{0}-t_{2}$$...$$t_{n - 1}-t_{n}$$, totally n^{2} / 2 sets?

**Comment by mohsenuss91** [comment]
@Jokeren  right, this is a unique label dataset.

**Comment by Jokeren** [comment]
Hi, I have updated a rough implementation in another branch : "feature". 

You can first check the correctness of the properties, then I will optimize the code and merge it into the master.

**Comment by mohsenuss91** [comment]
@Jokeren Where I can find it ! can you give me the properties of chemical_340 and compound_422 please?

**Comment by Jokeren** [comment]
Just run the program, and it will print properties into the log.

**Comment by mohsenuss91** [comment]
@Jokeren  I tried 

```
./gspan -file Chemical_340 -support 0.5 &> log_03112015
```

And It works, 
but i didn't understand some parts in the result.. 
what do you mean by "sep" ?

Some parts are empty! 
for example:

```
unique edge label set of 113 and 121 
113 : 
3 
121 : 
```

Can you simplify this by deleting the empty results ?

PS: please check the density and average size counting parts, I tried it with different datasets, I'm not sure but I thing it's giving a wrong results.

**Comment by Jokeren** [comment]
1. `sep` indicates "seperator" in graph files, currently you can avoid it.
2. I have simplified the label set in the lastest version.
3. Average size counting is updated.

**Comment by mohsenuss91** [comment]
@jokeren Thanks for your hard work.  
Please add the number of the  frequent found sub-graphs in the begging of the log file (so the user can directely read the result).

Can you explain this example for me please!

```
unique edge label set of 337 and 338 
337 : 
1 
338 : 
2 
```

PS: we say that a dataset has "a unique labelling graphs"only if:
                      for every graph: 
                                         edges labels are not found in another graph.

**Comment by Jokeren** [comment]
1. what do you mean "the begging of the log file", current format is :
   [subgraph_id] : [number of frequent subgraphs]
2. I recheck the edges in t337 and t338:

t 338
e 0 1 3
e 1 2 3
e 2 3 3
e 3 4 3
e 4 5 3
e 5 0 3
e 4 6 0
e 3 7 0
e 2 8 0
e 1 9 0
e 0 10 0
e 5 11 0
e 7 12 2
e 9 13 2

t 337
e 10 11 3
e 11 12 3
e 12 13 3
e 13 14 3
e 14 15 3
e 15 10 3
e 11 16 0
e 12 17 0
e 14 18 0
e 15 19 0
e 3 20 0
e 20 10 0
e 20 21 0
e 20 22 0
e 22 23 0
e 22 24 1
e 23 25 0
e 25 26 0
e 25 27 0
e 25 28 0
e 26 29 0
e 26 30 0
e 26 31 0
e 21 32 0
e 0 33 0
e 13 34 0

Comparing "t 337" with "t 338", "t 337" has the unique label 1, and "t 338" has the unique label 2.

Probabaly, what you mean is that find graphs, which obtain all the labels different with all the other graphs in the same file?

**Comment by mohsenuss91** [comment]
@Jokeren  I mean that the number of the discovered frequent subgraph must be on the top of the log file, just like average size of graphs and by a **_unique labeling dataset**_ I mean that : 
if "x" is a label of an edge, a unique labelling dataset must have "x" only one time in **all the dataset** (not only in one graph ).

**Comment by Jokeren** [comment]
1. I would not add this feature, since it requires adding a little bit of tricky codes. Besides, the information could be easily obtained by `grep "t #" logxxxx`.
2. I update the feature, and I guess that there are few unique labels in my dataset.

**Comment by mohsenuss91** [comment]
@Jokeren  OK, thank you and good luck :)
